services:
  db:
#    image: mysql:5.7
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: 'delivery'
    # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
    # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
    # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  dbdata: